In [2]:
import pandas as pd

In [3]:
hero_tier_list = pd.read_csv("data/hero_tier_list.csv").drop(columns=["Unnamed: 3"])
hero_tier_list[hero_tier_list["Name"] == "Frank"]

     Name Position Tier
50  Frank      Mid    A
98  Frank      Top    S

In [4]:
# Numeric map of tiers 
tier_map = {
    "S": 5,
    "A": 4,
    "B": 3,
    "C": 2,
    "D": 1
}

hero_tier_list["tier_score"] = hero_tier_list["Tier"].map(tier_map)
heros = hero_tier_list["Name"].unique().tolist()
print(heros[:5])

['Ada', 'BaJie', 'Bariel', 'Bond', 'Bunu Shan']

In [8]:
def get_hero_best_positions(hero_name: str | list[str], tier=1, verbose=False) -> dict[str, list[dict]]:
    output = {}

    names = [hero_name] if isinstance(hero_name, str) else hero_name.copy()

    for name in names:
        hero_rows = hero_tier_list[hero_tier_list["Name"] == name]
        max_score = hero_rows["tier_score"].max()
        target_score = max_score - (tier - 1)

        best_positions = hero_rows.loc[
            hero_rows["tier_score"] == target_score,
            ["Position", "Tier"]
        ].to_dict("records")

        if not best_positions:
            print(f"No heroes found under the name {name}.")
            continue

        position_names = [position["Position"] for position in best_positions]
        print_out = f"{name}'s best position is {', '.join(position_names)}."

        if verbose:
            print(print_out)

        output[name] = best_positions

    return output

#best_positions = get_hero_best_positions(["Ada", "Felyn", "Foso", "Frank"], verbose=True)
best_positions = get_hero_best_positions("Cubey", verbose=True, tier=1)
print(best_positions)

Cubey's best position is Mid, Top.
{'Cubey': [{'Position': 'Mid', 'Tier': 'A'}, {'Position': 'Top', 'Tier': 'A'}]}

In [7]:
# Get the best heroes for a position
def get_position_best_heroes(position: str | list[str], tier=1, verbose=False) -> dict[str, list[dict]]:
    output = {}

    positions = [position] if isinstance(position, str) else position.copy()

    for position in positions:
        position_rows = hero_tier_list[hero_tier_list["Position"] == position]
        max_score = position_rows["tier_score"].max()
        target_score = max_score - (tier - 1)

        best_heroes = position_rows.loc[
            position_rows["tier_score"] == target_score,
            ["Name", "Tier"]
        ].to_dict("records")

        if not best_heroes:
            print(f"No heroes found for the {position} position.")
            continue

        hero_names = [hero["Name"] for hero in best_heroes]
        print_out = f"Best heroes for the {position.lower()} position are {', '.join(hero_names)}."

        if verbose:
            print(print_out)

        output[position] = best_heroes

    return output

get_position_best_heroes(["Top", "Mid"], verbose=True)

Best heroes for the top position are Frank, Kid, Wukong, Foso.
Best heroes for the mid position are Aurelio, Merisi, Wolfgang, Foso.

{'Top': [{'Name': 'Frank', 'Tier': 'S'},
  {'Name': 'Kid', 'Tier': 'S'},
  {'Name': 'Wukong', 'Tier': 'S'},
  {'Name': 'Foso', 'Tier': 'S'}],
 'Mid': [{'Name': 'Aurelio', 'Tier': 'S'},
  {'Name': 'Merisi', 'Tier': 'S'},
  {'Name': 'Wolfgang', 'Tier': 'S'},
  {'Name': 'Foso', 'Tier': 'S'}]}

In [ ]:
# Build graph
import networkx as nx
import pandas as pd

data = pd.read_csv("data/hero_relationships.csv", keep_default_na=False).drop(columns=["Unnamed: 7", "Global Notes"])

graph = nx.DiGraph()

,name,synergies,counters,countered_by,tags,anti-synergy
0,Manta,Dylan,"Bart,Armour_Tank",None,"True Damage,Assassin,Crit",
1,Mihawk,"Search,Discard,Justice,Bond",Tank,None,True Damage,
2,Digo,Tank,"Armour,Assassin",None,True Damage,
3,Lubos,Targeting,None,Anna,"Targeting,Assassin",
4,Xiangxi Ke,Targeting,"Squishy,Backline",None,"Targeting,Assassin",
...,...,...,...,...,...,...
61,Dylan,"Search,Funnel",None,None,"Support,Buff",
62,Fatty White,None,"Targeting_Assassin,Debuff",Multi-Attacker,"Armour,Tank,Dispell",
63,Paisai,"Multi-Attacker,Merisi",None,Assassin,"Support,AP Buff",
64,Peiniang Zhu,"Multi-Attacker,AoE",None,"Wukong,Blocker","Support,AP Buff",
65,Anna,Skirmisher,"Skirmisher,Armour,Round 1 Damage,One Slap Chap",None,"Support,Skirmisher",